<?xml version="1.0" encoding="UTF-8"?><testrun name="TryMoveTest" project="HA2VorgabeWS19" tests="8" started="8" failures="1" errors="0" ignored="0">
  <testsuite name="de.tuberlin.sese.swtpp.gameserver.test.ploy.TryMoveTest" time="0.021">
    <testcase name="moveNotFigureTest" classname="de.tuberlin.sese.swtpp.gameserver.test.ploy.TryMoveTest" time="0.005"/>
    <testcase name="moveTest" classname="de.tuberlin.sese.swtpp.gameserver.test.ploy.TryMoveTest" time="0.002"/>
    <testcase name="moveNotOwnedTest" classname="de.tuberlin.sese.swtpp.gameserver.test.ploy.TryMoveTest" time="0.002"/>
    <testcase name="notMovingTest" classname="de.tuberlin.sese.swtpp.gameserver.test.ploy.TryMoveTest" time="0.001"/>
    <testcase name="rotationTest" classname="de.tuberlin.sese.swtpp.gameserver.test.ploy.TryMoveTest" time="0.002"/>
    <testcase name="obligedMoveTest" classname="de.tuberlin.sese.swtpp.gameserver.test.ploy.TryMoveTest" time="0.005">
      <failure>java.lang.AssertionError: expected:&lt;false&gt; but was:&lt;true&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at de.tuberlin.sese.swtpp.gameserver.test.ploy.TryMoveTest.assertMove(TryMoveTest.java:50)
	at de.tuberlin.sese.swtpp.gameserver.test.ploy.TryMoveTest.obligedMoveTest(TryMoveTest.java:166)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

</failure>
    </testcase>
    <testcase name="finishedGameTest" classname="de.tuberlin.sese.swtpp.gameserver.test.ploy.TryMoveTest" time="0.002"/>
    <testcase name="badMoveString" classname="de.tuberlin.sese.swtpp.gameserver.test.ploy.TryMoveTest" time="0.001"/>
  </testsuite>
</testrun>
